std = "lua51"
max_line_length = false

read_globals = {
	"BOT_ACTION_DESIRE_ABSOLUTE",
	"BOT_ACTION_DESIRE_HIGH",
	"BOT_ACTION_DESIRE_LOW",
	"BOT_ACTION_DESIRE_MODERATE",
	"BOT_ACTION_DESIRE_NONE",
	"BOT_ACTION_DESIRE_VERYHIGH",
	"BOT_ACTION_DESIRE_VERYLOW",
	"BOT_MODE_ATTACK",
	"BOT_MODE_DEFEND_TOWER_BOT",
	"BOT_MODE_DEFEND_TOWER_MID",
	"BOT_MODE_DEFEND_TOWER_TOP",
	"BOT_MODE_FARM",
	"BOT_MODE_GANK",
	"BOT_MODE_LANING",
	"BOT_MODE_NONE",
	"BOT_MODE_PUSH_TOWER_BOT",
	"BOT_MODE_PUSH_TOWER_MID",
	"BOT_MODE_PUSH_TOWER_TOP",
	"BOT_MODE_RETREAT",
	"BOT_MODE_ROSHAN",
	"DAMAGE_TYPE_ALL",
	"DAMAGE_TYPE_MAGICAL",
	"DAMAGE_TYPE_PHYSICAL",
	"DAMAGE_TYPE_PURE",
	"DotaTime",
	"GetBot",
	"GetLaneFrontLocation",
	"GetRoshanDesire",
	"GetScriptDirectory",
	"GetTeam",
	"GetUnitList",
	"GetUnitToLocationDistance",
	"GetUnitToUnitDistance",
	"IsLocationPassable",
	"LANE_BOT",
	"LANE_MID",
	"LANE_TOP",
	"RandomVector",
	"TEAM_DIRE",
	"TEAM_RADIANT",
	"UNIT_LIST_ALLIED_HEROES",
	"UNIT_LIST_ENEMY_HEROES",
	"UNIT_LIST_NEUTRAL_CREEPS",
}

globals = {
	"AbilityUsageThink",
	"BuybackUsageThink",
	"CourierUsageThink",
	"GetDesire",
	"ItemPurchaseThink",
	"MinionThink",
	"Think",
	"UpdateItemBuild",
}
